'use client';
import * as React from 'react';
import {createTheme, CssBaseline, ThemeProvider} from '@mui/material';

const customTheme = {
    description: 'TYPE: CUSTOM\nMaterial Theme Builder export 2025-06-14 01:01:16',
    seed: '#769CDF',
    coreColors: {
        primary: '#769CDF',
    },
    extendedColors: [],
    schemes: {
        light: {
            primary: '#415F91',
            surfaceTint: '#415F91',
            onPrimary: '#FFFFFF',
            primaryContainer: '#D6E3FF',
            onPrimaryContainer: '#284777',
            secondary: '#565F71',
            onSecondary: '#FFFFFF',
            secondaryContainer: '#DAE2F9',
            onSecondaryContainer: '#3E4759',
            tertiary: '#705575',
            onTertiary: '#FFFFFF',
            tertiaryContainer: '#FAD8FD',
            onTertiaryContainer: '#573E5C',
            error: '#BA1A1A',
            onError: '#FFFFFF',
            errorContainer: '#FFDAD6',
            onErrorContainer: '#93000A',
            background: '#F9F9FF',
            onBackground: '#191C20',
            surface: '#F9F9FF',
            onSurface: '#191C20',
            surfaceVariant: '#E0E2EC',
            onSurfaceVariant: '#44474E',
            outline: '#74777F',
            outlineVariant: '#C4C6D0',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#2E3036',
            inverseOnSurface: '#F0F0F7',
            inversePrimary: '#AAC7FF',
            primaryFixed: '#D6E3FF',
            onPrimaryFixed: '#001B3E',
            primaryFixedDim: '#AAC7FF',
            onPrimaryFixedVariant: '#284777',
            secondaryFixed: '#DAE2F9',
            onSecondaryFixed: '#131C2B',
            secondaryFixedDim: '#BEC6DC',
            onSecondaryFixedVariant: '#3E4759',
            tertiaryFixed: '#FAD8FD',
            onTertiaryFixed: '#28132E',
            tertiaryFixedDim: '#DDBCE0',
            onTertiaryFixedVariant: '#573E5C',
            surfaceDim: '#D9D9E0',
            surfaceBright: '#F9F9FF',
            surfaceContainerLowest: '#FFFFFF',
            surfaceContainerLow: '#F3F3FA',
            surfaceContainer: '#EDEDF4',
            surfaceContainerHigh: '#E7E8EE',
            surfaceContainerHighest: '#E2E2E9',
        },
        'light-medium-contrast': {
            primary: '#133665',
            surfaceTint: '#415F91',
            onPrimary: '#FFFFFF',
            primaryContainer: '#506DA0',
            onPrimaryContainer: '#FFFFFF',
            secondary: '#2E3647',
            onSecondary: '#FFFFFF',
            secondaryContainer: '#646D80',
            onSecondaryContainer: '#FFFFFF',
            tertiary: '#452E4A',
            onTertiary: '#FFFFFF',
            tertiaryContainer: '#7F6484',
            onTertiaryContainer: '#FFFFFF',
            error: '#740006',
            onError: '#FFFFFF',
            errorContainer: '#CF2C27',
            onErrorContainer: '#FFFFFF',
            background: '#F9F9FF',
            onBackground: '#191C20',
            surface: '#F9F9FF',
            onSurface: '#0F1116',
            surfaceVariant: '#E0E2EC',
            onSurfaceVariant: '#33363E',
            outline: '#4F525A',
            outlineVariant: '#6A6D75',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#2E3036',
            inverseOnSurface: '#F0F0F7',
            inversePrimary: '#AAC7FF',
            primaryFixed: '#506DA0',
            onPrimaryFixed: '#FFFFFF',
            primaryFixedDim: '#375586',
            onPrimaryFixedVariant: '#FFFFFF',
            secondaryFixed: '#646D80',
            onSecondaryFixed: '#FFFFFF',
            secondaryFixedDim: '#4C5567',
            onSecondaryFixedVariant: '#FFFFFF',
            tertiaryFixed: '#7F6484',
            onTertiaryFixed: '#FFFFFF',
            tertiaryFixedDim: '#654C6B',
            onTertiaryFixedVariant: '#FFFFFF',
            surfaceDim: '#C5C6CD',
            surfaceBright: '#F9F9FF',
            surfaceContainerLowest: '#FFFFFF',
            surfaceContainerLow: '#F3F3FA',
            surfaceContainer: '#E7E8EE',
            surfaceContainerHigh: '#DCDCE3',
            surfaceContainerHighest: '#D1D1D8',
        },
        'light-high-contrast': {
            primary: '#032B5B',
            surfaceTint: '#415F91',
            onPrimary: '#FFFFFF',
            primaryContainer: '#2A497A',
            onPrimaryContainer: '#FFFFFF',
            secondary: '#232C3D',
            onSecondary: '#FFFFFF',
            secondaryContainer: '#41495B',
            onSecondaryContainer: '#FFFFFF',
            tertiary: '#3A2440',
            onTertiary: '#FFFFFF',
            tertiaryContainer: '#59405E',
            onTertiaryContainer: '#FFFFFF',
            error: '#600004',
            onError: '#FFFFFF',
            errorContainer: '#98000A',
            onErrorContainer: '#FFFFFF',
            background: '#F9F9FF',
            onBackground: '#191C20',
            surface: '#F9F9FF',
            onSurface: '#000000',
            surfaceVariant: '#E0E2EC',
            onSurfaceVariant: '#000000',
            outline: '#292C33',
            outlineVariant: '#464951',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#2E3036',
            inverseOnSurface: '#FFFFFF',
            inversePrimary: '#AAC7FF',
            primaryFixed: '#2A497A',
            onPrimaryFixed: '#FFFFFF',
            primaryFixedDim: '#0E3262',
            onPrimaryFixedVariant: '#FFFFFF',
            secondaryFixed: '#41495B',
            onSecondaryFixed: '#FFFFFF',
            secondaryFixedDim: '#2A3344',
            onSecondaryFixedVariant: '#FFFFFF',
            tertiaryFixed: '#59405E',
            onTertiaryFixed: '#FFFFFF',
            tertiaryFixedDim: '#412A47',
            onTertiaryFixedVariant: '#FFFFFF',
            surfaceDim: '#B8B8BF',
            surfaceBright: '#F9F9FF',
            surfaceContainerLowest: '#FFFFFF',
            surfaceContainerLow: '#F0F0F7',
            surfaceContainer: '#E2E2E9',
            surfaceContainerHigh: '#D3D4DB',
            surfaceContainerHighest: '#C5C6CD',
        },
        dark: {
            primary: '#AAC7FF',
            surfaceTint: '#AAC7FF',
            onPrimary: '#0A305F',
            primaryContainer: '#284777',
            onPrimaryContainer: '#D6E3FF',
            secondary: '#BEC6DC',
            onSecondary: '#283141',
            secondaryContainer: '#3E4759',
            onSecondaryContainer: '#DAE2F9',
            tertiary: '#DDBCE0',
            onTertiary: '#3F2844',
            tertiaryContainer: '#573E5C',
            onTertiaryContainer: '#FAD8FD',
            error: '#FFB4AB',
            onError: '#690005',
            errorContainer: '#93000A',
            onErrorContainer: '#FFDAD6',
            background: '#111318',
            onBackground: '#E2E2E9',
            surface: '#111318',
            onSurface: '#E2E2E9',
            surfaceVariant: '#44474E',
            onSurfaceVariant: '#C4C6D0',
            outline: '#8E9099',
            outlineVariant: '#44474E',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#E2E2E9',
            inverseOnSurface: '#2E3036',
            inversePrimary: '#415F91',
            primaryFixed: '#D6E3FF',
            onPrimaryFixed: '#001B3E',
            primaryFixedDim: '#AAC7FF',
            onPrimaryFixedVariant: '#284777',
            secondaryFixed: '#DAE2F9',
            onSecondaryFixed: '#131C2B',
            secondaryFixedDim: '#BEC6DC',
            onSecondaryFixedVariant: '#3E4759',
            tertiaryFixed: '#FAD8FD',
            onTertiaryFixed: '#28132E',
            tertiaryFixedDim: '#DDBCE0',
            onTertiaryFixedVariant: '#573E5C',
            surfaceDim: '#111318',
            surfaceBright: '#37393E',
            surfaceContainerLowest: '#0C0E13',
            surfaceContainerLow: '#191C20',
            surfaceContainer: '#1D2024',
            surfaceContainerHigh: '#282A2F',
            surfaceContainerHighest: '#33353A',
        },
        'dark-medium-contrast': {
            primary: '#CDDDFF',
            surfaceTint: '#AAC7FF',
            onPrimary: '#002551',
            primaryContainer: '#7491C7',
            onPrimaryContainer: '#000000',
            secondary: '#D4DCF2',
            onSecondary: '#1D2636',
            secondaryContainer: '#8891A5',
            onSecondaryContainer: '#000000',
            tertiary: '#F3D2F7',
            onTertiary: '#331D39',
            tertiaryContainer: '#A487A9',
            onTertiaryContainer: '#000000',
            error: '#FFD2CC',
            onError: '#540003',
            errorContainer: '#FF5449',
            onErrorContainer: '#000000',
            background: '#111318',
            onBackground: '#E2E2E9',
            surface: '#111318',
            onSurface: '#FFFFFF',
            surfaceVariant: '#44474E',
            onSurfaceVariant: '#DADCE6',
            outline: '#AFB2BB',
            outlineVariant: '#8E9099',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#E2E2E9',
            inverseOnSurface: '#282A2F',
            inversePrimary: '#294878',
            primaryFixed: '#D6E3FF',
            onPrimaryFixed: '#00112B',
            primaryFixedDim: '#AAC7FF',
            onPrimaryFixedVariant: '#133665',
            secondaryFixed: '#DAE2F9',
            onSecondaryFixed: '#081121',
            secondaryFixedDim: '#BEC6DC',
            onSecondaryFixedVariant: '#2E3647',
            tertiaryFixed: '#FAD8FD',
            onTertiaryFixed: '#1D0823',
            tertiaryFixedDim: '#DDBCE0',
            onTertiaryFixedVariant: '#452E4A',
            surfaceDim: '#111318',
            surfaceBright: '#43444A',
            surfaceContainerLowest: '#06070C',
            surfaceContainerLow: '#1B1E22',
            surfaceContainer: '#26282D',
            surfaceContainerHigh: '#313238',
            surfaceContainerHighest: '#3C3E43',
        },
        'dark-high-contrast': {
            primary: '#EBF0FF',
            surfaceTint: '#AAC7FF',
            onPrimary: '#000000',
            primaryContainer: '#A6C3FC',
            onPrimaryContainer: '#000B20',
            secondary: '#EBF0FF',
            onSecondary: '#000000',
            secondaryContainer: '#BAC3D8',
            onSecondaryContainer: '#030B1A',
            tertiary: '#FFE9FF',
            onTertiary: '#000000',
            tertiaryContainer: '#D8B8DC',
            onTertiaryContainer: '#16041D',
            error: '#FFECE9',
            onError: '#000000',
            errorContainer: '#FFAEA4',
            onErrorContainer: '#220001',
            background: '#111318',
            onBackground: '#E2E2E9',
            surface: '#111318',
            onSurface: '#FFFFFF',
            surfaceVariant: '#44474E',
            onSurfaceVariant: '#FFFFFF',
            outline: '#EEEFF9',
            outlineVariant: '#C0C2CC',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#E2E2E9',
            inverseOnSurface: '#000000',
            inversePrimary: '#294878',
            primaryFixed: '#D6E3FF',
            onPrimaryFixed: '#000000',
            primaryFixedDim: '#AAC7FF',
            onPrimaryFixedVariant: '#00112B',
            secondaryFixed: '#DAE2F9',
            onSecondaryFixed: '#000000',
            secondaryFixedDim: '#BEC6DC',
            onSecondaryFixedVariant: '#081121',
            tertiaryFixed: '#FAD8FD',
            onTertiaryFixed: '#000000',
            tertiaryFixedDim: '#DDBCE0',
            onTertiaryFixedVariant: '#1D0823',
            surfaceDim: '#111318',
            surfaceBright: '#4E5056',
            surfaceContainerLowest: '#000000',
            surfaceContainerLow: '#1D2024',
            surfaceContainer: '#2E3036',
            surfaceContainerHigh: '#393B41',
            surfaceContainerHighest: '#45474C',
        },
    },
    palettes: {
        primary: {
            '0': '#000000',
            '5': '#00102B',
            '10': '#001B3E',
            '15': '#002551',
            '20': '#002F64',
            '25': '#033A77',
            '30': '#194683',
            '35': '#285290',
            '40': '#365E9D',
            '50': '#5177B8',
            '60': '#6B91D3',
            '70': '#86ACF0',
            '80': '#AAC7FF',
            '90': '#D6E3FF',
            '95': '#ECF0FF',
            '98': '#F9F9FF',
            '99': '#FDFBFF',
            '100': '#FFFFFF',
        },
        secondary: {
            '0': '#000000',
            '5': '#09111E',
            '10': '#141C29',
            '15': '#1E2634',
            '20': '#29313F',
            '25': '#343C4A',
            '30': '#3F4756',
            '35': '#4B5362',
            '40': '#575E6F',
            '50': '#707788',
            '60': '#8991A2',
            '70': '#A4ABBD',
            '80': '#BFC6D9',
            '90': '#DBE2F6',
            '95': '#ECF0FF',
            '98': '#F9F9FF',
            '99': '#FDFBFF',
            '100': '#FFFFFF',
        },
        tertiary: {
            '0': '#000000',
            '5': '#1B0A21',
            '10': '#27142C',
            '15': '#321F37',
            '20': '#3D2942',
            '25': '#49344D',
            '30': '#553F59',
            '35': '#614B65',
            '40': '#6E5772',
            '50': '#886F8B',
            '60': '#A288A6',
            '70': '#BEA2C1',
            '80': '#DABDDD',
            '90': '#F7D9FA',
            '95': '#FFEBFE',
            '98': '#FFF7FB',
            '99': '#FFFBFF',
            '100': '#FFFFFF',
        },
        neutral: {
            '0': '#000000',
            '5': '#101113',
            '10': '#1B1B1E',
            '15': '#252628',
            '20': '#303033',
            '25': '#3B3B3E',
            '30': '#464649',
            '35': '#525255',
            '40': '#5E5E61',
            '50': '#77777A',
            '60': '#919093',
            '70': '#ACABAE',
            '80': '#C7C6C9',
            '90': '#E3E2E5',
            '95': '#F2F0F3',
            '98': '#FAF9FC',
            '99': '#FDFBFF',
            '100': '#FFFFFF',
        },
        'neutral-variant': {
            '0': '#000000',
            '5': '#0E1117',
            '10': '#191C22',
            '15': '#23262C',
            '20': '#2E3037',
            '25': '#393B42',
            '30': '#44474D',
            '35': '#505259',
            '40': '#5C5E65',
            '50': '#75777E',
            '60': '#8E9098',
            '70': '#A9ABB3',
            '80': '#C5C6CE',
            '90': '#E1E2EA',
            '95': '#EFF0F9',
            '98': '#F9F9FF',
            '99': '#FDFBFF',
            '100': '#FFFFFF',
        },
    },
};

const theme = createTheme({
    palette: {
        mode: 'light', // You can change this to "dark" or dynamically set it
        primary: {
            main: customTheme.schemes.light.primary,
            light: customTheme.palettes.primary[80],
            dark: customTheme.palettes.primary[20],
            contrastText: customTheme.schemes.light.onPrimary,
        },
        secondary: {
            main: customTheme.schemes.light.secondary,
            light: customTheme.palettes.secondary[80],
            dark: customTheme.palettes.secondary[20],
            contrastText: customTheme.schemes.light.onSecondary,
        },
        tertiary: {
            main: customTheme.schemes.light.tertiary,
            light: customTheme.palettes.tertiary[80],
            dark: customTheme.palettes.tertiary[20],
            contrastText: customTheme.schemes.light.onTertiary,
        },
        error: {
            main: customTheme.schemes.light.error,
            light: customTheme.palettes.primary[80], // Using primary palette as a fallback for light/dark if not explicitly in customTheme's error palette
            dark: customTheme.palettes.primary[20], // Same as above
            contrastText: customTheme.schemes.light.onError,
        },
        background: {
            default: customTheme.schemes.light.background,
            paper: customTheme.schemes.light.surface,
        },
        text: {
            primary: customTheme.schemes.light.onBackground,
            secondary: customTheme.schemes.light.onSurfaceVariant,
        },
        // You can add more palette colors here based on your needs, e.g., info, success, warning
        // For example, if you want to explicitly define 'info', 'success', 'warning' from custom theme:
        info: {
            main: customTheme.palettes.primary[40], // Using primary as an example if not explicitly defined
            contrastText: customTheme.schemes.light.onPrimary,
        },
        success: {
            main: customTheme.palettes.neutral[60], // Using neutral as an example
            contrastText: customTheme.schemes.light.onSurface,
        },
        warning: {
            main: customTheme.palettes.tertiary[60], // Using tertiary as an example
            contrastText: customTheme.schemes.light.onTertiary,
        },
        // Adding custom colors from the scheme and palettes
        outline: customTheme.schemes.light.outline,
        outlineVariant: customTheme.schemes.light.outlineVariant,
        // Add grey palette as it's often useful and used in your components
        grey: {
            50: customTheme.palettes.neutral[95],
            100: customTheme.palettes.neutral[90],
            200: customTheme.palettes.neutral[80],
            300: customTheme.palettes.neutral[70],
            400: customTheme.palettes.neutral[60],
            500: customTheme.palettes.neutral[50],
            600: customTheme.palettes.neutral[40],
            700: customTheme.palettes.neutral[30],
            800: customTheme.palettes.neutral[20],
            900: customTheme.palettes.neutral[10],
        },
    },
    shape: {
        borderRadius: 8, // Less rounded corners
    },
    components: {
        MuiCard: {
            styleOverrides: {
                root: {
                    padding: '24px', // Add padding around all cards
                    // Only apply hover to most nested cards
                    transition: 'box-shadow 0.3s, transform 0.3s',
                    boxShadow: 3,
                    position: 'relative',
                    cursor: 'pointer',
                    zIndex: 1,
                    // Stronger hover effect for more nested cards
                    '&:hover': {
                        boxShadow: 12,
                        transform: 'translateY(-4px) scale(1.02)',
                        zIndex: 2,
                    },
                    // 2nd level nested card
                    '&.mui-nested-2:hover': {
                        boxShadow: 16,
                        transform: 'translateY(-8px) scale(1.04)',
                        zIndex: 3,
                    },
                    // 3rd level nested card
                    '&.mui-nested-3:hover': {
                        boxShadow: 20,
                        transform: 'translateY(-12px) scale(1.06)',
                        zIndex: 4,
                    },
                    // 4th level nested card (if any)
                    '&.mui-nested-4:hover': {
                        boxShadow: 24,
                        transform: 'translateY(-16px) scale(1.08)',
                        zIndex: 5,
                    },
                    // Remove pointer and transform for the background card only
                    '&[data-background-card="true"]': {
                        cursor: 'default',
                        '&:hover': {
                            boxShadow: 8,
                            transform: 'none',
                            zIndex: 1,
                        },
                    },
                    '@media (hover: none)': {
                        '&:hover': {
                            boxShadow: 3,
                            transform: 'none',
                            zIndex: 1,
                        },
                    },
                },
            },
        },
        MuiCardContent: {
            styleOverrides: {
                root: {
                    padding: '0', // Remove default CardContent padding, since Card has it
                },
            },
        },
    },
    typography: {
        fontFamily: 'Roboto, "Helvetica Neue", Arial, sans-serif',
    },
});

export default function MuiProvider({children}: { children: React.ReactNode }) {
    return (
        <ThemeProvider theme={theme}>
            <CssBaseline/>
            {children}
        </ThemeProvider>
    );
}
